### ISSUE TITLE
Missing tag on GitHub

### ISSUE THREAD

**Issue by franzlst** [maheshmnj/searchfield#103]
We are using [ort](https://github.com/oss-review-toolkit/ort/) for automatic software compliance checks.

searchfield is one of our dependencies and we use it in version 0.8.4. Now, ort fails in scanning this repo, as this version is not tagged on GitHub.

Could you please add the missing tag "0.8.4" to GitHub and keep these tags in sync with upcoming releases?

**Comment by maheshmnj** [comment]
Sounds Good!

**Comment by maheshmnj** [comment]
Closing the latest release is tagged.

**Comment by franzlst** [comment]
Thanks a lot!
