### ISSUE TITLE
[Proposal] Add `autoFocus` parameter to Searchfield

### ISSUE THREAD

**Issue by franzlst** [maheshmnj/searchfield#105]
**Is your feature request related to a problem? Please describe.**
Internally, `SearchField` uses `TextFormField`, which offers a parameter `autofocus`, allowing to retrieve the focus if no other element requests it. I would like `SearchField` to have the same feature.

**Describe the solution you'd like**
I propose to add the parameter `autofocus` to the `SearchField` widget and pass it to `TextFormField`.

**Comment by maheshmnj** [comment]
Thanks for filing the issue @franzlst, feel free to submit a PR if you are interested.

**Comment by maheshmnj** [comment]
Closing as fixed in [v0.8.8](https://pub.dev/packages/searchfield/changelog)

**Comment by franzlst** [comment]
Awesome, thank you for implementing this so quickly!
