### ISSUE TITLE
GestureDetector is not for SearchField

### ISSUE THREAD

**Issue by vignesh235** [maheshmnj/searchfield#107]
GestureDetector(
              onTap: () {
                print(
                    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddd");
              },
              child: SearchField(
                controller: controller,
                searchInputDecoration: InputDecoration(
                  labelText: label,
                  labelStyle: const TextStyle(color: Colors.black),
                  border: const OutlineInputBorder(
                      borderSide: BorderSide(color: Color(0x0ff2d2e4))),
                  focusedBorder: const OutlineInputBorder(
                      borderSide: BorderSide(color: Colors.black)),
                ),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return errorMessage;
                  }

                  return null;
                },
                suggestions: suggestion
                    .map((String) => SearchFieldListItem(String))
                    .toList(),
                suggestionStyle: const TextStyle(fontSize: 16),
                suggestionState: Suggestion.expand,
                suggestionsDecoration: SuggestionDecoration(
                    padding:
                        const EdgeInsets.only(top: 10.0, left: 5, bottom: 20),
                    color: const Color(0xFFEDEFFE),
                    borderRadius: const BorderRadius.all(Radius.circular(5))),
                textInputAction: TextInputAction.next,
                marginColor: const Color(0xFFEDEFFE),
                searchStyle: TextStyle(
                  fontSize: 17,
                  color: Colors.black.withOpacity(0.8),
                ),
                onSearchTextChanged: (p0) {
                  searching.searchname(controller.text, doctype);
                  return null;
                },
              ),
            ),

**Comment by vignesh235** [comment]
@maheshmnj  I want to call the API function while tap the search field and assign the value through the API function.

**Comment by maheshmnj** [comment]
@vignesh235, If i understand it right you want to call your api when searchfield is tapped (meaning searchfield gains focus) is that correct?

If so have you tried using focusNode?

**Comment by vignesh235** [comment]
Yes the tap is not triggered.

**Comment by maheshmnj** [comment]
@vignesh235  Exposed onTap method to SearchField which should help you with your use case.

Closing as fixed in [v0.9.0](https://pub.dev/packages/searchfield/changelog)

**Comment by maheshmnj** [comment]
@vignesh235 I have also added a sample example to load suggestions from network , please see the readme for sample code https://github.com/maheshmnj/searchfield
