### ISSUE TITLE
Suggestions Elevation same like dropdown button 

### ISSUE THREAD

**Issue by WaseemAbbasi22** [maheshmnj/searchfield#110]
Thanks for such awesome package  i just want a small improvement with the suggestion decoration i want elevation same like normal dropdown buttons options has cool elevation you have the suggestionDecoration with boxshow property but it's not working properly if color is same with the screen background  and also hide the suggestion when user scroll on the other part of screen or disable the scroll when suggestions are showing same like dropdown buttons 

**Describe the solution you'd like**
The most simple solution is to wrap the suggestions containers with Material and add elevation property and add a parameter of suggestionElevation to make it dynamic any one can set it according to the requirements 

**Describe alternatives you've considered**
alternate solution would be adding a card instead of container 

**Additional context**
<img width="307" alt="Screenshot 2024-02-15 at 11 33 52 AM" src="https://github.com/maheshmnj/searchfield/assets/50428976/8c670a0a-9372-4529-a68b-398004a225b9">
i want this to look like this

**Comment by WaseemAbbasi22** [comment]
final Widget listView = Material(
            elevation:widget.suggestionsDecoration?.elevation?? 8,
            borderRadius: widget.suggestionsDecoration?.borderRadius ??
                BorderRadius.zero,
            child: ListView.builder(
              reverse: _suggestionDirection == SuggestionDirection.up,
              padding: EdgeInsets.zero,
              controller: _scrollController,
              itemCount: snapshot.data!.length, wrap listview with material  and also need to remove  "ClipRRect" 
return Positioned(
              left: offset.dx,
              width: textFieldsize.width,
              child: CompositedTransformFollower(
                  offset: widget.offset ?? yOffset,
                  link: _layerLink,
                  child: ClipRRect(
                    borderRadius: widget.suggestionsDecoration?.borderRadius ??
                        BorderRadius.zero,
                    child: Material(
                      child: _suggestionsBuilder(),
                    ),
                  )),
            );
//replace with this 
  return Positioned(
              left: offset.dx,
              width: textFieldsize.width,
              child: CompositedTransformFollower(
                  offset: widget.offset ?? yOffset,
                  link: _layerLink,
                  child: _suggestionsBuilder()),
            ); 

add elevation parameter to the suggestion decoration

**Comment by maheshmnj** [comment]
Hi @WaseemAbbasi22, 
Thanks for filing the issue, elevation is required I will get this out ASAP.

**Comment by maheshmnj** [comment]
Bumping down the priority of this doesn't look straightforward to me. Also, this is not really a show-stopper so the package should work as intended. I'll come back to this issue soon.

**Comment by maheshmnj** [comment]
released in [v0.9.8](https://pub.dev/packages/searchfield/changelog).
Thank you for your contribution!
