### ISSUE TITLE
Hover color of the suggestion item

### ISSUE THREAD

**Issue by innodep-joonk** [maheshmnj/searchfield#112]
Thank you so much for creating an amazing package. 
I have one question: how can I add a hover color to the suggestion item?

**Comment by maheshmnj** [comment]
@innodep-joonk  Thanks for filing the issue, I am currently working on this should be out in couple of hours.

**Comment by maheshmnj** [comment]
@innodep-joonk  Released in [v0.9.6](https://pub.dev/packages/searchfield/changelog) Thank you for using the package. Feel free to leave feedback or report any issues you encounter.

Thank you for your contribution!

Best
Mahesh
