### ISSUE TITLE
Enter key doesn't seem to work

### ISSUE THREAD

**Issue by innodep-joonk** [maheshmnj/searchfield#119]
**Describe the bug**
After the keyboard arrow key function was added, the Enter key does not seem to work.

**To Reproduce**
1. Enter a value using the keyboard in the searchfield
2. Press Enter key

**Expected behavior**
When you press the Enter key, the onSubmit function must be executed.

**Actual behavior**
Even if I enter a value in the searchfield with the keyboard and press the Enter key, there is no response.

**Additional context**
[√] Flutter (Channel stable, 3.16.2, on Microsoft Windows [Version 10.0.22621.3155])
    • Flutter version 3.16.2 on channel stable at C:\DevSoftware\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (3 months ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

**Comment by innodep-joonk** [comment]
I'm so sorry. It was my environmental problem.

**Comment by maheshmnj** [comment]
@innodep-joonk After you enter the value in the searchfield, you cannot directly press enter you will need to select the option using arrow keys and then press enter. Let me know if that doesn't work.

**Comment by maheshmnj** [comment]
Closing this issue as Stale and nonreproducible. In case you still encounter this issue, Please feel free to write back and I would be happy to review.
