### ISSUE TITLE
Assertion failed: flutter/packages/flutter/lib/src/widgets/overlay.dart:168:12 _overlay != null is not true

### ISSUE THREAD

**Issue by murvkins** [maheshmnj/searchfield#124]
**Describe the bug**
I am receiving the error:
Assertion failed: file:///D:/flutter/packages/flutter/lib/src/widgets/overlay.dart:168:12
_overlay != null
is not true
It appears to be this line in your package: packages/searchfield/src/searchfield.dart 391:24 

The solution appears to be to add:
_overlayEntry = null 
just after line 391 per this SO: https://stackoverflow.com/questions/51443904/packageflutter-src-widgets-overlay-dart-failed-assertion-line-133-pos-12

**Comment by maheshmnj** [comment]
Hi @murvkins, Thanks for filing the issue. Is the issue.
 Is the issue with latest version of the package v0.9.7? if Yes,  Can you please share a minimal and complete code sample that I can run to debug the issue?

**Comment by murvkins** [comment]
I apologize.  I had only updated the Searchfield package to 0.9.7 from 0.8.7 at the time of writing.  After performing a flutter clean, updating the rest of my packages and my project, the issue is resolved.

**Comment by maheshmnj** [comment]
@murvkins No problem at all, we all have been there. I'm glad to hear it is working fine. If you encounter any issues or have any questions, please do not hesitate to file a issue or leave a comment.

Best,
Mahesh
