### ISSUE TITLE
Filtering Suggestion List then Using Arrow Keys and Enter not returning expected result

### ISSUE THREAD

**Issue by murvkins** [maheshmnj/searchfield#126]
**Describe the bug**
If you type a letter or two in the SearchField to filter the suggestions, then use the arrow keys to select one of the filtered items and press Enter, the item of the unfiltered suggestion list at the index of the selected item of the filtered list is returned instead.

**To Reproduce**
Using the example code on pub.dev, click in the Basic SearchField and type "d", then arrow down with "DEF" highlighted and press enter.  The resulting text in the SearchField is "ABC" instead of "DEF".

**Comment by maheshmnj** [comment]
Hello @murvkins, Thanks for filing the issue. I was able to reproduce the issue.

**Comment by maheshmnj** [comment]
fixed in [v0.9.9](https://pub.dev/packages/searchfield/changelog)
Thank you for your contribution!
