### ISSUE TITLE
Initialize selected with initialValue

### ISSUE THREAD

**Issue by franzlst** [maheshmnj/searchfield#127]
`_SearchFieldState` maintains a `selected` item, which currently only represents the item the user selects via hovering. In my point of view, this value should be initialized not with `null`, but with the element specified via `initialValue`. This should cause the initial value to be shown as selected.

**Comment by maheshmnj** [comment]
Thanks for the catch,  sounds good to me. A new release is on the way I will submit a fix with it.

**Comment by maheshmnj** [comment]
released in [v0.9.8](https://pub.dev/packages/searchfield/changelog).
Thank you for your contribution!

**Comment by franzlst** [comment]
@maheshmnj Thanks a lot for this quick fix and your work on the extension in general!
