### ISSUE TITLE
Blank results field displayed when an invalid entry is made.

### ISSUE THREAD

**Issue by murvkins** [maheshmnj/searchfield#132]
**Describe the bug**
Searchfield 1.0.0 bug.
If text is entered into a Searchfield that has no matches in the suggestionlist, there is a blank list displayed.  The blank list is not present in 0.9.9 and is the expected result.

**To Reproduce**
Using the sample code on the Searchfield pub.dev, type random text into a Searchfield to see the resulting blank field.

[ ] By clicking this checkbox, I confirm I am using the latest version of the package found on [pub.dev/searchfield](https://pub.dev/packages/searchfield)

**Screenshots**
![image](https://github.com/maheshmnj/searchfield/assets/151895144/bec43114-8710-4354-8dbc-8e37ca1187f3)

**Comment by maheshmnj** [comment]
Thanks for the catch @murvkins,

**Comment by maheshmnj** [comment]
Fixed in [v1.0.1](https://pub.dev/packages/searchfield/changelog)
