### ISSUE TITLE
suggestions do now show after textfieldfocus has changed

### ISSUE THREAD

**Issue by larsvombruch** [maheshmnj/searchfield#14]
The suggestion do only show automatically when the user manually taps on the SearchField, and not when the focus shifts to another one using `searchInputAction`

I would suggest opening the suggestions in the focusNode listener instead of the `onTap` property of the textfield, so that the suggestions show on every focus change

**Comment by maheshmnj** [comment]
@larsvombruch Thanks for filing the issue. I can reproduce it, `SearchField` only expands on tap and not on focus change, That looks like a valid proposal to me.

```dart
Column(
    mainAxisAlignment: MainAxisAlignment.spaceBetween,
   children: [
      const SizedBox(
         height: 20,
      ),
      const TextField(
         textInputAction: TextInputAction.next,
      ),
      SearchField(
          suggestionState: SuggestionState.enabled,
          suggestions: const [
             'United States',
             'America',
             'Washington',
             'India',
             'Paris',
             'Jakarta',
             'Australia',
             'Lorem Ipsum'
          ],
          searchInputAction: TextInputAction.next,
      ),
      const SizedBox(
      height: 20,
     ),
  ],
),
```

I will take a look at it this weekend, If you are interested you are welcome to send a PR :)

**Comment by larsvombruch** [comment]
@maheshmnj I have sent a PR :) Also added some extra features, such as `SuggestionAction`.

**Comment by maheshmnj** [comment]
Closing as PR has been merged.
