### ISSUE TITLE
Add Max Length and Option to disable counter for TextFormField

### ISSUE THREAD

**Issue by luckycreationsindia** [maheshmnj/searchfield#145]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add two parameters and link to TextFormField for maxLength and option to disable counter (if required)

**Describe alternatives you've considered**
None

**Additional context**

To hide counter - in TextFormField  we can add:

**buildCounter: (BuildContext context, { int currentLength, int maxLength, bool isFocused }) => null**

or user can specify in decoration parameter like below:

**decoration: InputDecoration(counterText: '')**

We can limit the length using input formatters (LengthLimitingTextInputFormatter(n)) but adding maxLength parameter will show counter too.

**Comment by maheshmnj** [comment]
Sounds good! Thanks for the PR.

**Comment by maheshmnj** [comment]
Published in [v1.0.4](https://pub.dev/packages/searchfield/changelog)

cc: @luckycreationsindia
