### ISSUE TITLE
An Overlay issue's occurs on Searchfield When a screen has Mutliple textfield .

### ISSUE THREAD

**Issue by ShafiMunshi** [maheshmnj/searchfield#148]
**Describe the bug**
My screen has multiple textfield and searchfield. After tapping on searchfield it show's all the suggestion , I choose one of them. then I input some data on other textfield. but when I try to change something in the previous searchfield again, it show's me this bug: 

The OverlayEntry was: OverlayEntry#a6732(opaque: false; maintainState: false)
The Overlay the OverlayEntry was trying to insert to was: OverlayState#37442(entries: [OverlayEntry#751ff(opaque: true; maintainState: false)
    entries: [OverlayEntry#751ff(opaque: true; maintainState: false), OverlayEntry#22623(opaque: false; maintainState: true)]
Consider calling remove on the OverlayEntry before inserting it to a different Overlay, or switching to the OverlayPortal API to avoid manual OverlayEntry management

**To Reproduce**
1. Make multiple textfield and searchfield
2. Click on searchfield and choose some suggestion or input some data
3 Click on a regular textfield , and input something, 
4. then again , click on the previous searchfield again. 
5.  See an overlay error

[ ] By clicking this checkbox, I confirm I am using the latest version of the package found on [pub.dev/searchfield](https://pub.dev/packages/searchfield)

**Expected behavior**
I don't want to expect any overlay issues

**Screenshots**
Error: 
![Screenshot from 2024-06-16 11-31-15](https://github.com/maheshmnj/searchfield/assets/69038196/4d6e8260-569f-4601-b74a-40da6ebcaacb)

**Code sample**
<details>
<summary>Show code sample</summary>

```dart  

// just a simple field to produce this bug

class TestScreen extends StatelessWidget {
  const TestScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final controller = TextEditingController();
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: [
          searchField('hinText', Icons.pedal_bike, ['shafi', 'rahat'], (val) {},
              controller),

              TextField(
                
              ),
        ],
      ),
    );
  }
}

```
</details>

**Additional context**

**Comment by maheshmnj** [comment]
Glad someone found this issue, initially reported https://github.com/maheshmnj/searchfield/issues/143

Caused by https://github.com/maheshmnj/searchfield/pull/142/files

**Comment by ShafiMunshi** [comment]
issues fixed.

**Comment by maheshmnj** [comment]
@ShafiMunshi Can you explain is this not an issue with searchfield?

**Comment by ShafiMunshi** [comment]
Oh, this issue has fixed by updated the latest version.,

**Comment by maheshmnj** [comment]
Thanks for the confirmation!
