### ISSUE TITLE
[Proposal] Support changing keyboardInputType

### ISSUE THREAD

**Issue by qxces** [maheshmnj/searchfield#16]
Can you add the ability to change the keyboard input type? e.g. ` textCapitalization: TextCapitalization.sentences,` and other.

**Comment by maheshmnj** [comment]
Looks like a valid proposal to me, You are welcome to send a PR if you are interested if not I will definitely fix it.

**Comment by maheshmnj** [comment]
This is available in `searchfield: ^0.6.2` https://pub.dev/packages/searchfield/changelog

Closing as fixed.
