### ISSUE TITLE
Keyboard isn't closing

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [maheshmnj/searchfield#19]
https://user-images.githubusercontent.com/49102327/155022251-9b0356b8-548d-42ce-89c5-5c68fc37e5d5.mov

**Comment by maheshmnj** [comment]
Hi @Shahmirzali-Huseynov, Thanks for filing the issue, from the video it looks like that issue should be filed in the flutter framework.

**Comment by Shahmirzali-Huseynov** [comment]
@maheshmnj there is no problem in the flutter framework. I forget to look at it here. But I have a question to you, I don't get what hasOverlay does in package? when I did hasOverlay: true it gives an error. when false there is no problem

 ```
               textInputAction: TextInputAction.done,
                hasOverlay: false,
                suggestionAction: SuggestionAction.unfocus,
```

**Comment by maheshmnj** [comment]
@Shahmirzali-Huseynov  with `hasOverlay: true` the suggestions are shown on top of other widgets (defaults to true) and if false the suggestions are shown immediately below the `SearchField` and you will see other widgets moving.

Can you please share the error that you are seeing ?

**Comment by Shahmirzali-Huseynov** [comment]
now I don't have an error, I have I will send it. But I have another error ) I opened issue
