### ISSUE TITLE
suggestion textStyle

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [maheshmnj/searchfield#22]
can you add custom field ?  - > `suggestionTextStyle : ,`

<img width="296" alt="Screen Shot 2022-02-25 at 11 05 16" src="https://user-images.githubusercontent.com/49102327/155678346-2fba8a67-0eca-4b54-85d8-be19e7557a3a.png">

**Comment by maheshmnj** [comment]
Hi @Shahmirzali-Huseynov I intentionally removed it since you could define a widget yourself

```dart
SearchFieldListItem<Country>(
        e.name,
        item: e,
       child: Text(e.name, style: YourTextStyle())
    ),
```
