### ISSUE TITLE
[Proposal]Support inputFormatters for the SearchField

### ISSUE THREAD

**Issue by Greshanw** [maheshmnj/searchfield#23]
It's better to add the "inputFormatters" as normal TextFormField. By that users developers easily add validations to searchfield.

**Comment by maheshmnj** [comment]
Hi @Greshanw, Thanks for filing the issue. I am quite not sure I understood the issue, Do you mean to support inputFormatters?

**Comment by maheshmnj** [comment]
Hi @Greshanw, Thanks for filing the issue. I am quite not sure I understood the issue, Do you mean to support inputFormatters?

**Comment by Greshanw** [comment]
Yeah thats what I meant.

**Comment by maheshmnj** [comment]
Fixed in [v0.6.6](https://pub.dev/packages/searchfield/changelog)

Thanks for the feature request.
