### ISSUE TITLE
How to  add custom sort logic  for already filtered data?

### ISSUE THREAD

**Issue by bartukaan** [maheshmnj/searchfield#26]
filteredList.sort((a, b) =>
              a.toLowerCase()
                .indexOf(filter)
                .compareTo(b.toLowerCase().indexOf(filter)

Can I add this kind of logic?

for example:
var streets = ["testabc","abc"];

when i will input search value "abc",
output suggestions will be : 1."testabc" 2."abc"
expected suggestions : 1."abc" 2."testabc"

so i want to output suggestions with more appropriate order by search value.

Thanks

**Comment by maheshmnj** [comment]
Hi @bartukaan, Thanks for filing the issue. Yes ofcourse you can add any kind of sort logic, That shouldn't be a problem, SearchField just requires you to return a List\<T>.

**Comment by bartukaan** [comment]
Hi @maheshmnj , thanks for reply.  
I handled it thanks.
