### ISSUE TITLE
Surface out TextFormField properties

### ISSUE THREAD

**Issue by jakegraves-figure** [maheshmnj/searchfield#28]
I love your library, but I'm frustrated that I can't access the `autocorrect` property of the TextFormField inside the SearchField.  

Please surface out this property so I can turn off the suggestive text. You might consider also including `enableSuggestions` of the TextFormField as well.

Thank you!

**Comment by maheshmnj** [comment]
HI @jakegraves-figure, Thanks for filing the issue. That's a fair ask.

**Comment by maheshmnj** [comment]
Fixed in [v0.6.6](https://pub.dev/packages/searchfield/changelog)

Thanks for the feature request.
