### ISSUE TITLE
flutter 3.0.0 update issue

### ISSUE THREAD

**Issue by vaisakhferoke** [maheshmnj/searchfield#29]
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/searchfield-0.6.4/lib/src/searchfield.dart:314:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    WidgetsBinding.instance!.addPostFrameCallback((_) {

                   ^

**Comment by maheshmnj** [comment]
Closing as fixed in 0.6.5 https://github.com/maheshmnj/searchfield/commit/ab2461771fd8393c31656a8971cd26534f8ba960
