### ISSUE TITLE
Height property for search field

### ISSUE THREAD

**Issue by lilvinco** [maheshmnj/searchfield#31]
Hi there,

Great package, a great time saver. 

It's quite frustrating though that the search field's height can not be customised. Would be nice to be able to constrain the height of the textfield at will, a possible way to go about it is wrapping the textfield with a SizeBox and exposing the height property.

**Comment by maheshmnj** [comment]
Hi @lilvinco, Thanks for filing the issue. That sounds like a nice feature request. Also, I see you submitted a PR that seems to be closed. In case you want to contribute feel free to, I would love to review if not I can definitely get that landed in a week.

**Comment by lilvinco** [comment]
Thanks for the feedback, I will now create a new PR

**Comment by maheshmnj** [comment]
Hi @lilvinco, Thanks for the PR. I was wondering of the usecase, where would we need to customize the height of the SearchField? since SearchField is always a singleliner. Even if you need this feature why not just wrap SearchField in SizedBox directly, wouldn't that work?

```dart
SizedBox(
  child: SearchField()
)
```

**Comment by lilvinco** [comment]
<img width="302" alt="Screenshot 2022-06-02 at 00 27 22" src="https://user-images.githubusercontent.com/15001773/171517964-cd8a9bd6-078c-4e92-b2a2-467fb63dc38e.png">
<img width="297" alt="Screenshot 2022-06-02 at 00 27 59" src="https://user-images.githubusercontent.com/15001773/171517974-a61d7f71-066b-43c3-980a-26258eb2b80a.png">
<img width="297" alt="Screenshot 2022-06-02 at 00 28 21" src="https://user-images.githubusercontent.com/15001773/171517977-66aadd0b-5f10-4f86-8bdb-7bf417f335c0.png">

**Comment by lilvinco** [comment]
1: searchableHeight : 50 is set
2. No height
3. Wrapped with SizedBox and set height property of 50

**Comment by maheshmnj** [comment]
@lilvinco Just checking with you, if you would be interested in working on this any time soon?

**Comment by lilvinco** [comment]
Oh yeah @maheshmnj 

I had worked on it but my PR was left unattended to for a long time

**Comment by maheshmnj** [comment]
Apologies for the delay @lilvinco, Now I am actively working on this package.

**Comment by lilvinco** [comment]
Alright, I'll review it again

**Comment by maheshmnj** [comment]
@lilvinco thanks for the PR it looks great, And I really appreciate the time and effort you put in to get the PR, But I think that change is not required now, Searchfield should respect Its parent constraints without this PR. You can directly wrap a searchfield with a SizedBox or a Container and it should work out of the box. Let me know if that doesn't work for you.

 If you encounter any other issues or have suggestions to improve this package, You are more than Welcome!
 
 Thank you again for your effort.
