### ISSUE TITLE
[proposal] Ability to configure scrollbar visibility 

### ISSUE THREAD

**Issue by msampathkumara** [maheshmnj/searchfield#33]
is there any way to make suggestion list scrollbar always visible ?

**Comment by maheshmnj** [comment]
Hi @msampathkumara, Thanks for filing the issue. Yes that should be possible.

**Comment by Shahmirzali-Huseynov** [comment]
@maheshmnj  yes, in the mobile will be good I think. thanks for your effort.

**Comment by maheshmnj** [comment]
@Shahmirzali-Huseynov this should be a simple fix if anyone of you would like to contribute feel free too, However, It will take me a wee, Probably to come back to this.

**Comment by msampathkumara** [comment]
Hi @maheshmnj ,
I want this on web.
now scrollbar is visible only when suggestion list is focused. I want it  visible when ever  suggestion list is visible..

**Comment by maheshmnj** [comment]
Update: there's a little issue with Scrollbar which I think is a bug in flutter I have filed that issue here  https://github.com/flutter/flutter/issues/106326

**Comment by maheshmnj** [comment]
> Update: there's a little issue with Scrollbar which I think is a bug in flutter I have filed that issue here https://github.com/flutter/flutter/issues/106326

Update: the flutter issue has been fixed in the flutter repo, The RawScrollbar has a property `padding` available on master but not on stable so this PR https://github.com/maheshmnj/searchfield/pull/60 (Which will close this issue) is waiting for the fix to land on the stable channel. Once it does this issue will be resolved.

**Comment by maheshmnj** [comment]
published [v0.7.5](https://pub.dev/packages/searchfield/changelog)
