### ISSUE TITLE
validation for Class model 

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [maheshmnj/searchfield#36]
How can I validate this? also can you add validation to your example county_search.dart sample.

```
SearchField(
                    focusNode: focus,
                    suggestions: countries
                        .map((country) =>
                            SearchFieldListItem(country.name, item: country))
                        .toList(),
                    suggestionState: Suggestion.expand,
                    controller: _searchController,
                    hint: 'Search by country name',
                    maxSuggestionsInViewPort: 4,
                 
                    itemHeight: 45,
                    inputType: TextInputType.text,
                    onSuggestionTap: (SearchFieldListItem<Country> x) {
                      setState(() {
                        _selectedCountry = x.item!;
                      });
                      focus.unfocus();
                    },
                  ),
```

**Comment by maheshmnj** [comment]
Hi @Shahmirzali-Huseynov, Thanks for filing the issue. Please see this example 

which wraps SearchField in Form and assigns a key 

https://github.com/maheshmnj/searchfield/blob/ed28e24360717c207168f854ddd6e2827323086c/example/lib/example1.dart#L84-L87

And then implement the validator function 

https://github.com/maheshmnj/searchfield/blob/ed28e24360717c207168f854ddd6e2827323086c/example/lib/example1.dart#L97-L101

and then invoke this function using the formKey

https://github.com/maheshmnj/searchfield/blob/69bc9585ebb5e2eb88f5a21f05910ab9ea3b81bc/example/lib/example1.dart#L196

I have updated the [country_search](https://github.com/maheshmnj/searchfield/blob/master/example/lib/country_search.dart) example to show validation for the custom class.

Closing as solved.
