### ISSUE TITLE
inputFormatter typo in the documentation

### ISSUE THREAD

**Issue by xxJeevesxx** [maheshmnj/searchfield#37]
**Describe the bug**
In the documentation on properties, the inputFormatter is listed, however when trying to add the inputFormatter as a property it errors as it doesn't exist. Also I can't find it in the code behind the SearchField widget. 

**To Reproduce**
1. Create search field widget in ui
2. Try to add inputFormatters as property

**Expected behavior**
inputFormatter be able to accept inputFormatters properties as listed in the documentation.

**Actual behavior**
an error is received that the property doesn't exist.

**Screenshots**
<img width="261" alt="Screen Shot 2022-06-16 at 8 53 36 PM" src="https://user-images.githubusercontent.com/3445444/174221632-5e9466a3-fda7-4739-98c6-5bfd134673a8.png">

Thanks in advance for any help you can provide.

**Comment by maheshmnj** [comment]
Hi @xxJeevesxx, Thanks for filing the issue. Please ensure you are using the latest version `searchfield: ^0.6.6`.  

I just verified it seems to work
<img width="344" alt="image" src="https://user-images.githubusercontent.com/31410839/174232016-9f284953-248d-49e3-a8b6-ef1afa87ecb7.png">

And it is "inputFormatters" (s) is missing, Looks like this is a bug in the documentation 

<img width="510" alt="image" src="https://user-images.githubusercontent.com/31410839/174232147-4c25ef86-e6bd-41cd-8ced-f12e928fb66f.png">


I hope you know this but still a heads up, if you are not sure if the property exist you can always peek into the source code from you IDE or hover and see the available properties

<img width="552" alt="image" src="https://user-images.githubusercontent.com/31410839/174232277-1479f424-90b2-461b-a52c-773a255ef499.png">


I am going to label this as a documentation bug, In case you are interested consider sending a PR.

Thanks

**Comment by xxJeevesxx** [comment]
Wow, I'm really sorry for the trouble. Looks like I had v0.6.5 which is why it didn't show up. I'm not sure how to do the whole PR thing otherwise I would try to help however I can. Again, sorry for the whole waste of time.

**Comment by maheshmnj** [comment]
Hey not really, This helped me figure out the typo.
Thanks for your report, In case you find any bugs or have a feature request I would encourage filing an issue and I would love to have a discussion about it.

Thanks

**Comment by xxJeevesxx** [comment]
Sounds good. Thanks again for the quick reply!

**Comment by maheshmnj** [comment]
fixed in https://github.com/maheshmnj/searchfield/commit/c99c2b5da1c5d65965d5422cd62e37668fae105e, This will be available on pub in upcoming release
