### ISSUE TITLE
Suggestions list not updating with state

### ISSUE THREAD

**Issue by exilonX** [maheshmnj/searchfield#39]
**Describe the bug**
I create a SearchField like below:

```
SearchField<Location?>(
  suggestions: widget.searchResults
      .map((e) => SearchFieldListItem<Location?>(
          e?.locationName?.text ?? '',
          child: SearchResultItem(
            item: e,
          )))
      .toList(),
  emptyWidget: const Text("Searching for results"),
  focusNode: _focusNode,
  textInputAction: TextInputAction.next,
  hint: 'Location name',
  searchStyle: TextStyle(
    fontSize: 18,
    color: Colors.black.withOpacity(0.8),
  ),
  searchInputDecoration: InputDecoration(
    focusedBorder: OutlineInputBorder(
      borderSide: BorderSide(
        color: Colors.black.withOpacity(0.8),
      ),
    ),
    border: const OutlineInputBorder(
      borderSide: BorderSide(color: Colors.red),
    ),
  ),
  maxSuggestionsInViewPort: 6,
  onSuggestionTap: (x) {
    print("Suggestion tap");
    print(x.item);
  },
  itemHeight: 50,
  controller: _controller,
),
```
The suggestions are passed from the parent widget, down to the widget that contains the SearchField.
The suggestions are initally an empty list [] and get updated once you enter something in the textFormField.
The parent widget is a ReduxConsumer.
Let's assume that when you enter more than 3 letters a network request is triggered which when finished, will populate the state with the result.

The problem is that even though widget.searchResults is not empty, the SearchField doesn't update it's state and expand the suggestions... It stays with the emptyWidget... 
But if I click outside and then again in the widget, I get suggestions... 

I even tried to `focusNode.requestFocus()` when I have searchResults but nothing really changes... 

**To Reproduce**
1. Create a SearchField that has some asyncronously populated searchResults
2. Write in the textField something
3. When more that 3 characters written, network request triggered 
4. On response, populate state

**Expected behavior**
I would expect that once my state gets updated with some suggestions, the widget should update also... 

**Actual behavior**
The widget remains unchanged as if it's still empty

**Comment by maheshmnj** [comment]
Hi @exilonX, Thanks for filing the issue. This has been on my list for a while. We can use this issue for tracking.

**Comment by exilonX** [comment]
Please tell me if you have a suggestion on how to implement this... I could give it a try :D

**Comment by maheshmnj** [comment]
@exilonX , The suggesttions right now are shown in two ways either below the searchfield as a list or in a overlay.
My guess is this issue is for the second case when `hasOverlay:true`, if that is the case, We need to look for how we can update the overlay state while it is still visible. I don't have an exact idea right now I will have to investigate too.
But Once I have any update or start a work I will link a PR and we can have further discussion there.

**Comment by maheshmnj** [comment]
@exilonX fixed in v0.6.7, 
Thanks for your contribution. If you see any issue again Please consider filing a new issue, It helps improve the package.

**Comment by exilonX** [comment]
Thank you so much @maheshmnj. It works great now! 

Unrelated to this issue, I only have one suggestion: if I choose to use an `emptyWidget` after selecting an item from the dropdown, the empty widget shows immediately after. 
Please give it a try, maybe it's something on my end :D

**Comment by maheshmnj** [comment]
Thanks for the feedback @exilonX, Glad it works. Regarding your other feedback could you please file a separate issue? I am guessing it is somewhat related to https://github.com/maheshmnj/searchfield/issues/32 (This is pending to be fixed, Because I don't have clarity on what the expected behaviour is)
