### ISSUE TITLE
Adding Text Alignment and Text style in the suggestion list that is generated.

### ISSUE THREAD

**Issue by panshulgarg** [maheshmnj/searchfield#40]
**Is your feature request related to a problem? Please describe.**
I want to add consistency to the text styles, in the suggestion box. Currently, it looks like it is fixed.

**Describe the solution you'd like**
The search field would accept params for the formatting details for the text shown in the suggestion list.

**Comment by maheshmnj** [comment]
Hi @panshulgarg, Thanks for filing the issue. You can do that as of today by specifying the child Property to `SearchFieldListItem`  

Heres a sample code and the output

```dart
 SearchField(
      suggestions: _statesOfIndia
      .map((e) => SearchFieldListItem(e,
          child: Align(
              alignment: Alignment.centerRight,
              child: Text(e,
                  style: TextStyle(color: Colors.red),
              ),
          )
        ).toList(),
...
...
)

```

<img width="341" alt="image" src="https://user-images.githubusercontent.com/31410839/183568683-4a0acbf2-9e9e-48c2-bf51-6ad32e81fe5d.png">

**Comment by maheshmnj** [comment]
Closing as this can be achieved as of today as per above https://github.com/maheshmnj/searchfield/issues/40#issuecomment-1208920478
