### ISSUE TITLE
Cleaning input

### ISSUE THREAD

**Issue by spadesM** [maheshmnj/searchfield#42]
Hi 

It is awesome. Is there any way to clean input after suggestion tap?

**Comment by maheshmnj** [comment]
Hi @spadesM, Glad you asked,

SearchField provides you with a `onSuggestionTap` callback which you can use to clear the textinput

```dart
  SearchField(
      ...
      onSuggestionTap: (){
        controller.clear();
      }
  )
``` 

Closing as this is neither a bug nor a feature request.
