### ISSUE TITLE
Remove unnecessary box underneath the suggestion box.  

### ISSUE THREAD

**Issue by romain-pattyn** [maheshmnj/searchfield#44]
Currently the SearchField widget enables us to modify the suggestion box decoration through the suggestionsDecoration parameter. However, when adding rounded corners to that box, there is still a white box underneath that makes the look really awkward. It can be seen in the next picture, the black lines at the bottom of the suggestion box (which is the black box) shouldn't stop before the black box.

<img width="434" alt="Capture d’écran 2022-08-09 à 15 18 42" src="https://user-images.githubusercontent.com/73311663/183656832-f8d0ce97-e71b-45af-abff-33ed825f368e.png">
 
This makes me believe that the suggestion box is somehow the child of a container that has a white fillColor or something like that. 

Would it be possible to remove that unnecessary box?

**Comment by romain-pattyn** [comment]
Actually removing that box doesn't fix the issue because of other artifact present in those unwanted areas. Such as the item separators (See image) or the scrollbar.

<img width="416" alt="Capture d’écran 2022-08-09 à 15 41 25" src="https://user-images.githubusercontent.com/73311663/183664614-21579162-60b4-41ff-a256-e1ddb7e0079d.png">

The way to go I think would be to add a ClipRRect widget in the parent tree of the suggestion box that we could modify through a new parameter in SearchField.

**Comment by maheshmnj** [comment]
Hi @romain-pattyn, Thanks for filing the issue. Can you please drop a small piece of a code sample that demonstrates the above output?

**Comment by romain-pattyn** [comment]
The following code will replicate the issue.

```
SearchField<String>(
  suggestions: [
    SearchFieldListItem("item1"),
    SearchFieldListItem("item2"),
    SearchFieldListItem("item3"),
    SearchFieldListItem("item4"),
    SearchFieldListItem("item5"),
    SearchFieldListItem("item6"),
  ],
  marginColor: Colors.orange,
  maxSuggestionsInViewPort: 3,
  searchInputDecoration: InputDecoration(
    focusedBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(24),
      borderSide: const BorderSide(
        width: 1,
        color: Colors.orange,
        style: BorderStyle.solid,
      ),
    ),
    border: OutlineInputBorder(
      borderRadius: BorderRadius.circular(24),
      borderSide: const BorderSide(
        width: 1,
        color: Colors.black,
        style: BorderStyle.solid,
      ),
    ),
    fillColor: Colors.white,
    filled: true,
    contentPadding: const EdgeInsets.symmetric(
      horizontal: 20,
    ),
  ),
  suggestionsDecoration: BoxDecoration(
    border: Border.all(color: Colors.orange),
    borderRadius: BorderRadius.circular(24),
  ),
);
```

To fix the issue we simply need to wrap the AnimatedContainer in a ClipRRect inside _suggestionsBuilder. 

There are another few improvements that could be made like being able to change the suggestionStyle. I would like to contribute to this package. Do I need to open a different feature request issue for each improvement I want to make?

**Comment by romain-pattyn** [comment]
I've fixed the issue, can I create a pull request? 
That's with the new version : 

<img width="491" alt="Capture d’écran 2022-08-10 à 12 13 09" src="https://user-images.githubusercontent.com/73311663/183876857-ec65fd8c-8db0-4a3e-adb2-32e8ff590e95.png">

Quick question : Why do we need to create a new branch when forking the repo to make a contribution?

**Comment by romain-pattyn** [comment]
The ClipRRect must actually be placed above the _suggestionBuilder() like so 👍 
```
CompositedTransformFollower(
    offset: getYOffset(offset, count) ?? Offset.zero,
    link: _layerLink,
    child: ClipRRect(
      borderRadius: widget.suggestionBoxBorderRadius,
      child: Material(
        child: _suggestionsBuilder(),
      ),
    ),
  ),
```

Doing so will also cut the InkWell color change.

**Comment by maheshmnj** [comment]
Thanks for the code sample I will surely take a look.

>  I would like to contribute to this package. 

Thank you so much, PR's are welcome, I would love to help you with the reviews. Before you begin please take a look at this contributing guide https://github.com/maheshmnj/searchfield/blob/master/CONTRIBUTING.md, Let me know if you have any questions.

> Do I need to open a different feature request issue for each improvement I want to make?

Yes please filing issues separately per feature request/bug would help us track it separately.

> I've fixed the issue, can I create a pull request?
That's with the new version :

Yes please file a PR and tag me and I will review it asap.


> Quick question : Why do we need to create a new branch when forking the repo to make a contribution?

That's a good practice to create a separate branch per feature. so that if we mess up anything we won't be affecting the main branch.

**Comment by beingadish** [comment]
**Hello, I would like to know if this issue is fixed or not. If not how to fix it I need to remove that background white colored container, my client is asking me to remove it somehow. I don't know what to do kindly someone help me fix that.**

**Comment by maheshmnj** [comment]
@beingadish Can you please provide a minimal reproducible code to better understand the issue, I am kind of lost with this issue at this time.
