### ISSUE TITLE
Adding a text style to the default suggestions

### ISSUE THREAD

**Issue by romain-pattyn** [maheshmnj/searchfield#45]
When no child is given to the SearchFieldListItem objects, it uses the search key as text for the suggestion.

I would simply like to add the possibility to modify the textStyle of that text.

**Comment by maheshmnj** [comment]
Thanks for filling the issue and the PR, Thats a fair ask.

**Comment by maheshmnj** [comment]
Will review the PRs tonight, I really appreciate you taking the time.

**Comment by maheshmnj** [comment]
published [searchfield: ^0.6.9](https://pub.dev/packages/searchfield)
