### ISSUE TITLE
Dispose on tap outiside

### ISSUE THREAD

**Issue by ggichure** [maheshmnj/searchfield#5]
Is there a way to dispose results on tap outside ?something  barrier dismissible in alert dialog.

**Comment by maheshmnj** [comment]
do you mean to collapse the suggestions on tapping outside the widget?

**Comment by ggichure** [comment]
Yes.
________________________________

**Comment by ggichure** [comment]
is it something feasible?

**Comment by maheshmnj** [comment]
yes ofcourse thats posssible if you check the example project it collapses the suggestions if tapped on the body of the Ui.Thats possible because we are removing the focus from UI by unfocusing like this . 
```
 onTap: () => FocusScope.of(context).unfocus(),
```
