### ISSUE TITLE
custom Y axis between search box and item box, current default is due to itemHeight

### ISSUE THREAD

**Issue by thegioiso** [maheshmnj/searchfield#50]
I created a search widget like below with overlay enabled: 
![image](https://user-images.githubusercontent.com/106056252/184851443-c58b1cef-3a17-4321-bf21-858e223e381a.png)

I changed itemHeight to 60 and a "transparent box" exist between my search box and item lists below.
![image](https://user-images.githubusercontent.com/106056252/184851731-dd2f1394-3c84-4508-a871-94cbc6b60f3c.png)

And when i changed itemHeight to 100. This y axis between 2 is increased too.
![image](https://user-images.githubusercontent.com/106056252/184851924-56f2fa37-22d9-4b34-90e3-caee0c7b290b.png)

I hope that i can remove or custom this "y transparent axis" in my project. Thank you all so much.

**Comment by maheshmnj** [comment]
Hi @thegioiso, Thanks for filing the issue. Can you please share a minimal and complete code sample that shows the issue?

**Comment by thegioiso** [comment]
Dear @maheshmnj, i create a sample code for this issue and i found out something: 
```
SizedBox(
          height: 50,
          width: 200,
          child: SearchField<dynamic>(
            itemHeight: 50.0,
            suggestions: [
              {
                "item": "itemA",
                "value": "valueA",
              },
              {
                "item": "itemB",
                "value": "valueB",
              }
            ]
                .map(
                  (e) => SearchFieldListItem<dynamic>(
                    e["item"] ?? "",
                    item: e,
                    child: Padding(
                      padding: const EdgeInsets.only(top: 5.0),
                      child: Text(e["value"] ?? ""),
                    ),
                  ),
                )
                .toList(),
          ),
        ),
 ```      
with `itemHeight = 50.0`, if item box overlay show at top position, every thing work fine:
![image](https://user-images.githubusercontent.com/106056252/185530041-12f8e128-04eb-4570-b929-bbcfecb0f4a0.png)

BUT, if overlay show at bottom position, it will create a "transparent space" between two:
![image](https://user-images.githubusercontent.com/106056252/185530141-4bd670c6-2cf8-4d9f-bf34-a0cd54639ef7.png)

change 'itemHeight = 200.0' and we will see this issue correctly:
![image](https://user-images.githubusercontent.com/106056252/185530248-db060898-2a1d-49c3-a907-87f0aeb86bad.png)

**Comment by thegioiso** [comment]
@maheshmnj and i found out the overlay always show on top position on Android, if the space is not enough will cause unmounted error. I hope we can custom overlay position to bottom or top. Thank you so much.

**Comment by maheshmnj** [comment]
Thanks for the info @thegioiso, I can reproduce the issue. Perhaps we can make it configurable. 
 
<img width="545" alt="Screenshot 2022-08-21 at 6 06 07 AM" src="https://user-images.githubusercontent.com/31410839/185770667-fe563782-70e6-4051-b83a-bfe39968f341.png">

**Comment by maheshmnj** [comment]
You may use temporary workAround `hasOverlay:false`

**Comment by thegioiso** [comment]
Dear @maheshmnj , use `hasOverlay: false` is a temporary solution and it will cause overflow problem seriously for my layout. But thank for your advice, i will try with Stack widget for some case needed.

And one more thing, if this issue is fixed, can you provide a parameter for set fixed position of overlay. Example:
- when set `overlayPosition: PreferredPosition.top`, suggest box will fixed at Top position. And `bottom` position too. Or `auto`, maybe at now - but when i try on Android, some case this auto really bad and make my suggest will under device status bar when show at top. That why i really hope this parameter. 

You may look around this pub package ` https://pub.dev/packages/custom_pop_up_menu/example `, they have a parameter `position: PreferredPosition.top` for this setting.

Thank for your works.

**Comment by maheshmnj** [comment]
Yes @thegioiso, I have planned to provide with an offset parameter that you can use to manually set the position of the Suggestions Overlay, I agree that the temporary workaround is not the right solution, it was just to unblock you immediately, However I have a fix in pipeline I intend to publish that this weekend, I really wish I could publish it tonight, But unfortunately I  am occupied with other work.

I will keep you updated.

**Comment by maheshmnj** [comment]
[v0.7.0](https://pub.dev/packages/searchfield/changelog) has been published.

**Comment by thegioiso** [comment]
@maheshmnj thank you so much, the new update worked perfectly.

**Comment by danishkhawaja98** [comment]
@maheshmnj can you share an example on how to fix the suggestion to the top?
