### ISSUE TITLE
Suggestion Box not closed after select the options

### ISSUE THREAD

**Issue by Nandhinidevi123** [maheshmnj/searchfield#53]
![Screenshot from 2022-10-07 18-12-27](https://user-images.githubusercontent.com/95607404/194556367-d9fab662-fd59-4390-99e7-33e6e2c6289d.png)

Suggestion Box not closed after select the options

**Comment by maheshmnj** [comment]
Hi @Nandhinidevi123, Thanks for filing the issue. Can you please share a minimal and complete code sample? Also do you see any error logs in the console?

**Comment by frodrigueztorres** [comment]
Hi, can confirm. It happens to me when i update to the last version (in 0.6.6 didn't happen), and there is no errors in the log. There is the code i use for the input

```  Widget build(BuildContext context) {
    return SearchField(
      hasOverlay: false,
      controller: controller,
      initialValue: initialValue,
      textInputAction: action,
      searchInputDecoration: InputDecoration(
        labelText: translationKey,
        border: const OutlineInputBorder(),
      ),
      suggestionsDecoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(10),
      ),
      itemHeight: 50,
      suggestions: items
    );
  ```

**Comment by maheshmnj** [comment]
@frodrigueztorres thanks for confirming, Can you please check if it occurs with latest v0.7.2? There have been bunch of fixes  since v0.6.6

**Comment by frodrigueztorres** [comment]
@maheshmnj It occurs with the latest versión. I tested with the `0.6.6`, `0.7.0` and `0.7.2` and only in `0.6.6` it worked correctly

**Comment by maheshmnj** [comment]
Thanks for checking @frodrigueztorres, I tried the below code sample and it seems to work fine.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:searchfield/searchfield.dart';

class DemoApp extends StatefulWidget {
  @override
  _DemoAppState createState() => _DemoAppState();
}

class _DemoAppState extends State<DemoApp> {
  final List<String> _suggestions = [
    'United States',
    'Germany',
    'Washington',
    'Paris',
    'Jakarta',
    'Australia',
    'India',
    'Czech Republic',
    'Lorem Ipsum',
  ];

  final List<String> _statesOfIndia = [
    'Andhra Pradesh',
    'Assam',
    'Arunachal Pradesh',
    'Bihar',
    'Goa',
    'Gujarat',
    'Jammu and Kashmir',
    'Jharkhand',
    'West Bengal',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Orissa',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Tripura',
    'Uttaranchal',
    'Uttar Pradesh',
    'Haryana',
    'Himachal Pradesh',
    'Chhattisgarh'
  ];

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          SearchField(
            suggestionItemDecoration: BoxDecoration(
              color: Colors.grey.withOpacity(0.2),
              gradient: LinearGradient(colors: [
                Color(0xff70e1f5),
                Color(0xffffd194),
              ], begin: Alignment.topLeft, end: Alignment.bottomRight),
            ),
            hasOverlay: false,
            suggestions:
                _suggestions.map((e) => SearchFieldListItem(e)).toList(),
            suggestionState: Suggestion.hidden,
            textInputAction: TextInputAction.next,
            initialValue: SearchFieldListItem(_suggestions.first),
            searchInputDecoration: InputDecoration(
              floatingLabelBehavior: FloatingLabelBehavior.auto,
              labelText: 'SearchField',
              border: OutlineInputBorder(),
            ),
            // hasOverlay: false,
            hint: 'SearchField example 4',
            maxSuggestionsInViewPort: 6,
            suggestionDirection: SuggestionDirection.down,
            itemHeight: 45,
            onSuggestionTap: (x) {},
          ),
        ],
      ),
    );
  }
}

```
</details> 

Can you please use this code sample and share a reproducible example?

**Comment by mwenechac** [comment]
@Nandhinidevi123, you may want to add focus nodes to your fields. See here: https://github.com/maheshmnj/searchfield/blob/master/example/lib/country_search.dart

**Comment by Hallykola** [comment]
> 

This work because your onSugestionTap is an empty function. Try adding some lines of code or statements to your onSugestionTap and the error will occur.

**Comment by Hallykola** [comment]
> Thanks for checking @frodrigueztorres, I tried the below code sample and it seems to work fine.
> 
> code sample
> ```dart
> import 'package:flutter/material.dart';
> import 'package:searchfield/searchfield.dart';
> 
> void main() {
>   runApp(MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>         title: 'Flutter Demo',
>         theme: ThemeData(
>           primarySwatch: Colors.blue,
>           visualDensity: VisualDensity.adaptivePlatformDensity,
>         ),
>         home:DemoApp());
>   }
> }
> 
> 
> class DemoApp extends StatefulWidget {
>   @override
>   _DemoAppState createState() => _DemoAppState();
> }
> 
> class _DemoAppState extends State<DemoApp> {
>   final List<String> _suggestions = [
>     'United States',
>     'Germany',
>     'Washington',
>     'Paris',
>     'Jakarta',
>     'Australia',
>     'India',
>     'Czech Republic',
>     'Lorem Ipsum',
>   ];
> 
>   final List<String> _statesOfIndia = [
>     'Andhra Pradesh',
>     'Assam',
>     'Arunachal Pradesh',
>     'Bihar',
>     'Goa',
>     'Gujarat',
>     'Jammu and Kashmir',
>     'Jharkhand',
>     'West Bengal',
>     'Karnataka',
>     'Kerala',
>     'Madhya Pradesh',
>     'Maharashtra',
>     'Manipur',
>     'Meghalaya',
>     'Mizoram',
>     'Nagaland',
>     'Orissa',
>     'Punjab',
>     'Rajasthan',
>     'Sikkim',
>     'Tamil Nadu',
>     'Tripura',
>     'Uttaranchal',
>     'Uttar Pradesh',
>     'Haryana',
>     'Himachal Pradesh',
>     'Chhattisgarh'
>   ];
> 
>   @override
>   Widget build(BuildContext context) {
>     return Material(
>       child: Column(
>         mainAxisAlignment: MainAxisAlignment.center,
>         children: [
>           SearchField(
>             suggestionItemDecoration: BoxDecoration(
>               color: Colors.grey.withOpacity(0.2),
>               gradient: LinearGradient(colors: [
>                 Color(0xff70e1f5),
>                 Color(0xffffd194),
>               ], begin: Alignment.topLeft, end: Alignment.bottomRight),
>             ),
>             hasOverlay: false,
>             suggestions:
>                 _suggestions.map((e) => SearchFieldListItem(e)).toList(),
>             suggestionState: Suggestion.hidden,
>             textInputAction: TextInputAction.next,
>             initialValue: SearchFieldListItem(_suggestions.first),
>             searchInputDecoration: InputDecoration(
>               floatingLabelBehavior: FloatingLabelBehavior.auto,
>               labelText: 'SearchField',
>               border: OutlineInputBorder(),
>             ),
>             // hasOverlay: false,
>             hint: 'SearchField example 4',
>             maxSuggestionsInViewPort: 6,
>             suggestionDirection: SuggestionDirection.down,
>             itemHeight: 45,
>             onSuggestionTap: (x) {},
>           ),
>         ],
>       ),
>     );
>   }
> }
> ```
> 
> Can you please use this code sample and share a reproducible example?

This work because your onSugestionTap is an empty function. Try adding some lines of code or statements to your onSugestionTap and the error will occur.

**Comment by maheshmnj** [comment]
@Hallykola Unfortunately I am unable to reproduce it, Please let me know if I am missing any step here. I won't be able to progress further on this issue unless I am able to reproduce it.
 
https://user-images.githubusercontent.com/31410839/208010140-a2ab08f9-e297-45db-9766-e01509824739.mov

**Comment by Nandhinidevi123** [comment]
ok fine
