### ISSUE TITLE
[ISSUE] Overlay shown on top of searchfield

### ISSUE THREAD

**Issue by maheshmnj** [maheshmnj/searchfield#6]
if  ```maxSuggestionsInViewPort``` value exceeds screen height and ```showOverlay``` is true ,then overlay is shown at top of the searchfield.

<img width="497" alt="Screenshot 2021-04-16 at 11 18 15 PM" src="https://user-images.githubusercontent.com/31410839/115064069-1d993000-9f0a-11eb-9f30-07dfa4b93c42.png">

**Comment by maheshmnj** [comment]
```maxSuggestionsinviewPort``` should have a  constraint

**Comment by karacaemre** [comment]
I'm still having this problem, even if I set `maxSuggestionsInViewPort` as 1, and `itemHeight` as 10. Any solutions?

![searchfieldbug](https://user-images.githubusercontent.com/59104216/197143841-7ca7daf0-1e3d-4dc7-8819-8703e3765118.png)

**Comment by maheshmnj** [comment]
@karacaemre as a temporary workaround, you can specify your custom offset, this way the overlay is always shown at a fix position and is not dynamically positioned

```dart
 offset: Offset(0, 50),
```

**Comment by maheshmnj** [comment]
[Released `v0.7.2`](https://pub.dev/packages/searchfield/changelog) which adds a new property `suggestionDirection` which should give you more flexibility to position the suggestions.

However, searchfield should support the dynamic positioning of suggestions based on the available space, this is being tracked here https://github.com/maheshmnj/searchfield/issues/56
