### ISSUE TITLE
How to remove divider in suggestion

### ISSUE THREAD

**Issue by vignesh235** [maheshmnj/searchfield#64]
![photo_2022-12-16_18-32-02](https://user-images.githubusercontent.com/95606753/208104301-5cb7e84c-e45d-4caa-94d1-93b649295113.jpg)

**Comment by maheshmnj** [comment]
Hi @vignesh235, Thanks for filing the issue. Please use the properties `suggestionItemDecoration`  and `suggestionDecoration` to style each suggestion and the list of suggestions respectively.


This is the default `suggestionItemDecoration` 
https://github.com/maheshmnj/searchfield/blob/c96fead5d07d79c0945e1f9ef66ef49d43cb7a29/lib/src/searchfield.dart#L483-L492

**Comment by maheshmnj** [comment]
Please feel free to close the issue if you think your query has been resolved.

**Comment by maheshmnj** [comment]
Closing as this is not really an issue and the requested feature can be achieved with the current implementation as mentioned in the above comments.
