### ISSUE TITLE
How to add padding in search suggestion ?

### ISSUE THREAD

**Issue by Sahil2710** [maheshmnj/searchfield#66]
![Simulator Screen Shot - iPhone 14 Pro Max - 2022-12-30 at 12 41 51](https://user-images.githubusercontent.com/80583549/210044441-d20cff98-f048-4545-8dd3-e0c973f64b48.png)

**Comment by maheshmnj** [comment]
@Sahil2710 SearchFieldListItem has a property `child` You can use it like this.

```dart
suggestions: countries
      .map((country) => SearchFieldListItem(country.name,
      item: country,
     child: Padding(
    padding: EdgeInsets.symmetric(horizontal: 16),
    child: Text(country.name),
  )))
.toList(),
```
Hope this answers your question.

**Comment by maheshmnj** [comment]
Closing as this is not really an issue and can be achieved with the current implementation as mentioned above.
