### ISSUE TITLE
[Web]`onSuggestionTap` not triggered on flutter stable 3.7

### ISSUE THREAD

**Issue by aglpy** [maheshmnj/searchfield#70]
Hi, 2 days ago the flutter team upgrade flutter to version 3.7, I don't know the reason but the onSuggestionTap function is not being triggered when we do tap on a suggestion. I am not sure about the origin of the problem to fix it, we have an app in production using devops so it automatically was build in flutter 3.7 yesterday and now our clients can't use our app.

Thanks.

**Comment by maheshmnj** [comment]
Thanks for reporting the bug @aglpy I haven't had a chance to upgrade to latest stable yet, I will triage this issue asap

**Comment by aglpy** [comment]
That sounds great but it probably means it is a problem with flutter web, with your info, I run the example in flutter web and it doesn't work, when you tap a suggestion the textfield is not filled. I run the tests and it works fine. Then, I installed the app in my Android device and it works fine, so maybe is like your ios simulator. Anyway I write here some changes I made to make it run in Android (if not, the app dind't even start) so I don't know if this changes solve the problem for any reason that the bug is.

android/gradle/wrapper/gradle-wrapper.properties:
`- distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip

\+ distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-all.zip`

android/gradle.properties:
`- org.gradle.jvmargs=-Xmx1536M

\+ org.gradle.jvmargs=-Xmx1536M \

\+ --add-exports=java.base/sun.nio.ch=ALL-UNNAMED \

\+ --add-opens=java.base/java.lang=ALL-UNNAMED \

\+ --add-opens=java.base/java.lang.reflect=ALL-UNNAMED \

\+ --add-opens=java.base/java.io=ALL-UNNAMED \

\+ --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED`

**Comment by ferwanguer** [comment]
Exact same issue here. At least it should be declared that the package is not compatible with web for the time being.

**Comment by maheshmnj** [comment]
Thanks for reporting the bug @aglpy I think that flutter did not break onTap, rather they fixed the race condition for focus and gesture events. I filed an issue though to get some more insights https://github.com/flutter/flutter/issues/119390

**Comment by maheshmnj** [comment]
Closing as fixed in https://github.com/maheshmnj/searchfield/pull/71
