### ISSUE TITLE
Set State call On Suggestion Tap

### ISSUE THREAD

**Issue by ilmirfan** [maheshmnj/searchfield#74]
I am trying to call a setState function On Suggestion Tap, but it prevents suggestion overly closing. Any suggestion to get it done? TIA

**Comment by maheshmnj** [comment]
Hello @ilmirfan, Could you please share a minimal and complete code sample for your usecase?

**Comment by ilmirfan** [comment]
Hi @maheshmnj Thanks for the reply. Something like this 

 onSuggestionTap: (value) {
                    setState(() {
                      doSomthing();
                    });
                  },

I am trying to refresh a listview based on the selected suggestion from SearchField. Without  setState cases it works perfectly. But when I use setState (It's kinda must) inside onSuggestionTap or through a function, the overly suggestion isn't closing. Not sure it's a bug, but if you could suggest me some solution would be great. TIA

**Comment by maheshmnj** [comment]
@ilmirfan ensure that you using the latest version of the package `searchfield: ^0.7.5`. And if I understand it correctly tapping the Does the issue reproduce with this [example app](https://github.com/maheshmnj/searchfield/blob/master/example/lib/country_search.dart)? it has the similar code sample you are talking about

https://github.com/maheshmnj/searchfield/blob/fb7f9c91afb554e27c4270f2a3d839de5b14f94e/example/lib/country_search.dart#L80-L84

 if the issue does not reproduce with the example app, can you modify and share the reproducible code?

**Comment by ilmirfan** [comment]
Sorry for late. Ye example app works. Should be wrong something in my code. I will inspect and update you. Thanks so much.
