### ISSUE TITLE
Add textCapitalization property

### ISSUE THREAD

**Issue by TomJFox** [maheshmnj/searchfield#77]
**Is your feature request related to a problem? Please describe.**
I would like to configure the textField created by SearchField with textCapitalization property.  
This would allow for Capitalization to be set on the field so that the value entered is automatically capitalized. See links in Additional Context below.

**Describe the solution you'd like**
Request textCapitalization is added to the properties which can be set on SearchField and the value (if set) is then passed to TextFormField when building.  TextFormField has this property, so the property simply needs to be exposed via SearchField and then passed to TextFormField.

**Describe alternatives you've considered**
I have added the property to the code myself, but would prefer it is added to SearchField, so all can take advantage.

**Additional context**
https://api.flutter.dev/flutter/material/TextField/textCapitalization.html 
https://api.flutter.dev/flutter/services/TextCapitalization.html

**Comment by maheshmnj** [comment]
Hi @TomJFox, Thanks for filing the issue. Feel free to file a PR if you are interested and I would be happy to review.

**Comment by maheshmnj** [comment]
Published [v0.7.8](https://pub.dev/packages/searchfield/changelog)
