### ISSUE TITLE
Feature suggestion - generically typed value

### ISSUE THREAD

**Issue by nmfisher** [maheshmnj/searchfield#8]
Great widget. Currently, this only works with Strings, have you considered adopting the same approach as the standard DropdownButton<T>, whereby each DropdownMenuItem<T> accepts a value of type T and the list is then built with an itemBuilder?

I know this was originally intended as a search field, but it would be nice to present suggestions while preserving some underlying value.

**Comment by maheshmnj** [comment]
Yes, definitely that would be a great add on I will be working on adding that feature may be by this weekend.

**Comment by maheshmnj** [comment]
Hi,  Thanks for filing the issue I was thinking about this and I realize that if we want to  generalize the type then we have to expose these three apis 
```
OptionsBuilder: A function which returns List<T> 
ListItemBuilder: A function which returns a List item widget
searchBuilder: A function which returns  a textfield as a searchfield
```
And probably we will have to ditch these apis 
 ```
initialValue,
validator
height,
suggestionItemDecoration,
hint,
searchInputDecoration
```

Let me know your thoughts.

**Comment by maheshmnj** [comment]
I am a bit busy with other work these days so I might need some more time, The Progress will be happening on the [feature branch](https://github.com/maheshmnj/searchfield/tree/feature/generalize-type), If you like you are welcome to send a PR :)

**Comment by MuhammadSufyanMalik** [comment]
> Hi, Thanks for filing the issue I was thinking about this and I realize that if we want to generalize the type then we have to expose these three apis
> 
> ```
> OptionsBuilder: A function which returns List<T> 
> ListItemBuilder: A function which returns a List item widget
> searchBuilder: A function which returns  a textfield as a searchfield
> ```
> 
> And probably we will have to ditch these apis
> 
> ```
> initialValue,
> validator
> height,
> suggestionItemDecoration,
> hint,
> searchInputDecoration
> ```
> 
> Let me know your thoughts.

Hi, Mahesh I would like to provide <DropdownMenuItem<String>>, because if I select any item it should give me its value.
any chance of achieving this ?

**Comment by maheshmnj** [comment]
Hi, I haven't had a chance to look into this, I will surely try to come up with a solution this week.

**Comment by MuhammadSufyanMalik** [comment]
> Hi, I haven't had a chance to look into this, I will surely try to come up with a solution this week.
Thanks for the immediate reply.
Can I set any value in the field from the list on page start?
I set the value in initialValue but it does not set in the field.
is there any other way, or I am missing any implementation?

**Comment by maheshmnj** [comment]
Make sure you are using the latest version `searchfield: ^0.5.6`, and initialValue that you add should be present in the list of suggestions

> initialValue : The initial value to be set in searchfield when its rendered, if not specified it will be empty.

**Comment by MuhammadSufyanMalik** [comment]
> Make sure you are using the latest version `searchfield: ^0.5.6`, and initialValue that you add should be present in the list of suggestions
> 
> > initialValue : The initial value to be set in searchfield when its rendered, if not specified it will be empty.

Yes, I am using the updated one and it is present also in the list as well. But it doesn't not display in the field.
Secondly, If I write any text other than list items the submit button doesn't  validate as far as I know from your documentation it should tell not available in the list if I press submit.

**Comment by maheshmnj** [comment]
Thanks for the info @MuhammadSufyanMalik, could you please file that as a separate bug, that issue seems to be different from this case.

**Comment by MuhammadSufyanMalik** [comment]
Okay, 

> Thanks for the info @MuhammadSufyanMalik, could you please file that as a separate bug, that issue seems to be different from this case.

Okay. but do let me know the solution if there is any.
Thanks

**Comment by maheshmnj** [comment]
Maybe you can try running the [example](https://github.com/maheshmnj/searchfield/tree/master/example) for now, will take a look at it today.

**Comment by MuhammadSufyanMalik** [comment]
Hi,
I am facing this issue while assigning InitailValue, can you help me out with this ?
Thanks

════════ Exception caught by scheduler library ═════════════════════════════════
type 'List<String?>' is not a subtype of type 'List<String>?' of 'data'
════════════════════════════════════════════════════════════════════════════════

**Comment by maheshmnj** [comment]
@nmfisher Update: generic typed value is added in `searchfield 0.6.1`, Heres the sample api usage 

```dart
SearchField(
    suggestions: countries
       .map((country) =>
       SearchFieldListItem(country.name, item: country))
       .toList(),
    suggestionState: Suggestion.expand,
    controller: _searchController,
    hint: 'Search by country name',
    maxSuggestionsInViewPort: 4,
    itemHeight: 45,
    onTap: (SearchFieldListItem x) {
    setState(() {
    _selectedCountry = x.item;
   });
  },
 ),
),
```

complete example for above snippet can be found here [example/country_search.dart](https://github.com/maheshmnj/searchfield/blob/master/example/lib/country_search.dart)

A complete changelog can be found here https://pub.dev/packages/searchfield/changelog

Thank you so much for your contribution, This PR actually helped me learn quite a few new things :)
In case you find any new bugs in the future, You are welcome to file new issues.

Closing as fixed

**Comment by maheshmnj** [comment]
@MuhammadSufyanMalik Hopefully this Release also fixes your issue, Incase it doesn't feel free to file a new issue with a sample code

**Comment by MuhammadSufyanMalik** [comment]
> @MuhammadSufyanMalik Hopefully this Release also fixes your issue, Incase it doesn't feel free to file a new issue with a sample code

Hi,
After updating at 0.6.1, I am getting suggestionStyle error.
: Error: No named parameter with the name 'suggestionStyle'.
lib/…/widgets/searchTextField.dart:60
          suggestionStyle: TextStyle(color: primaryBlue, fontSize: fontSize12),
          ^^^^^^^^^^^^^^^
/[C:/Users/muhammad.sufyan/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/searchfield-0.6.1/lib/src/searchfield.dart:198:3](): Context: Found this candidate, but the arguments don't match.
  SearchField({
  ^^^^^^^^^^^
   could you please check this first ?
