### ISSUE TITLE
add onInputType function to update suggestions list

### ISSUE THREAD

**Issue by arifikhsan** [maheshmnj/searchfield#80]
**Is your feature request related to a problem? Please describe.**
I want to be able to update the suggestions as i type on the input form

**Describe the solution you'd like**
add a `onInputType` that called after user change the search value

**Additional context**
 I need to update the suggestions list that will be retrieved from backend

**Comment by maheshmnj** [comment]
Hello @arifikhsan, thanks for the feature request, I have been thinking about this and we recently had a discussion here https://github.com/maheshmnj/searchfield/issues/78.
Please follow up on that issue for further updates closing this issue as a duplicate.

Thank you.

**Comment by arifikhsan** [comment]
allright thank you so much @maheshmnj
