### ISSUE TITLE
[Web]: Overlay dimensions do not update when the window size changes

### ISSUE THREAD

**Issue by maheshmnj** [maheshmnj/searchfield#84]
Update overlay dimensions when the window size changes.

### Steps to Reproduce

1. Run the sample app
<img width="612" alt="Screenshot 2023-05-19 at 9 05 02 PM" src="https://github.com/maheshmnj/searchfield/assets/31410839/b7d5c50c-69e0-4030-92de-32a066fe785a">

2. Resize the window and notice the overlay stays in old dimensions

<img width="997" alt="Screenshot 2023-05-19 at 9 05 24 PM" src="https://github.com/maheshmnj/searchfield/assets/31410839/e3d4791d-6801-4941-8ca8-aedab33919f8">

**Comment by maheshmnj** [comment]
complete code sample here https://gist.github.com/maheshmnj/7b3f135f090647c6ab64fb49e207f495

**Comment by RamiroNoronha** [comment]
I am having the same problem, but I am using windows plataform. Do you have some date to fix this? Thanks for helping! :D

**Comment by maheshmnj** [comment]
There should be some way to reposition it, I am not sure How though, But I will try to dig in this weekend.

**Comment by maheshmnj** [comment]
@RamiroNoronha Fixed in the latest release
Apologies for the delay

https://github.com/maheshmnj/searchfield/assets/31410839/f886cf5e-a093-45af-9fa6-433c3b719070

**Comment by maheshmnj** [comment]
Released in [v0.9.1](https://pub.dev/packages/searchfield/changelog)
