### ISSUE TITLE
Small-screen phones bug 

### ISSUE THREAD

**Issue by roshan-gh** [maheshmnj/searchfield#9]
At the small-screen phones (in my case it's Nexus 4), search suggestions with 1 result, it has a bug like the screenshot I attached. The search suggestion can't display properly.
![image](https://user-images.githubusercontent.com/76537930/131186283-f5288781-816e-4eed-ba92-fb56b985ab5f.png)

**Comment by maheshmnj** [comment]
Hi is the issue solved?

**Comment by roshan-gh** [comment]
> Hi is the issue solved?

Hi, yes, my friend solved it. For small screens it should have change the overlay settings. 
And thanks for this package. It's useful.

**Comment by maheshmnj** [comment]
Glad it is solved, Feel free to report any issues or make a feature request this would help to maintain this package.
