### ISSUE TITLE
keyboard covers suggestions menu

### ISSUE THREAD

**Issue by heshesh2010** [maheshmnj/searchfield#97]
Hi , using latest version , I notice that when the search field in the last widget in the screen in the bottom , when keyboard shows I see it covers the drop menu  , I try to set     resizeToAvoidBottomInset: true, but it shows only the textfield , 

screenshot attached 

![WhatsApp Image 2023-09-29 at 12 05 19 AM](https://github.com/maheshmnj/searchfield/assets/16393042/06f9a156-52bd-4700-8f3e-bfa3f38ad411)

**Comment by maheshmnj** [comment]
Hi @heshesh2010,

Thanks for filing the issue. Can you try adding the `offset` parameter which basically offsets the suggestion list overlay

**Comment by heshesh2010** [comment]
> Hi @heshesh2010,
> 
> Thanks for filing the issue. Can you try adding the `offset` parameter which basically offsets the suggestion list overlay

@maheshmnj thank u it's working now when set    offset: Offset(0, -50),
