### ISSUE TITLE
Hint Style

### ISSUE THREAD

**Issue by AscanioB** [maheshmnj/searchfield#98]
Perhaps I'm missing something but there doesn't seem to be an option to change the hint style.

**Comment by maheshmnj** [comment]
Hello @AscanioB, Thanks for filing the issue. I am sorry the documentation couldn't help to answer this.
You should be able to change the hintStyle using `searchInputDecoration: InputDecoration.hintStyle`

```dart
searchInputDecoration: InputDecoration(
   hintStyle: TextStyle(color: Colors.red)
),
```

The api is desigend in a way that to decorate the searchfield input use `searchInputDecoration` and for decorating suggestions use `suggestionsDecoration`

I hope this answers your question.

**Comment by AscanioB** [comment]
Yes how silly of me, thanks.

**Comment by maheshmnj** [comment]
Happens to the best of us :)
